#!/usr/bin/env sh

version=$(jq -r '.version' package.json)
echo "// This file is autogenerated by scripts/save-version.sh" > src/version.ts
echo "// Do not edit it manually!" >> src/version.ts
echo "export const LIB_VERSION = '${version}'" >> src/version.ts
