#!/usr/bin/env sh

version=$(jq -r '.version' package.json)
echo "/**" > src/metadata.ts
echo " * These values are used for the default footer in Slack message and in logging." >> src/metadata.ts
echo " *" >> src/metadata.ts
echo " * @privateRemarks" >> src/metadata.ts
echo " * This file is autogenerated by scripts/save-metadata.sh" >> src/metadata.ts
echo " * Do not edit it manually!" >> src/metadata.ts
echo " *" >> src/metadata.ts
echo " * @internal" >> src/metadata.ts
echo " */" >> src/metadata.ts
echo "export const LIB_VERSION = '${version}'" >> src/metadata.ts
if [ "${GITHUB_ACTIONS}" = "true" ]; then
  sha="$(git rev-parse HEAD)"
  build_at="$(date +"%Y-%m-%dT%H:%M:%S%z")"
else
  sha="foo (dev)"
  build_at="1900-01-01T00:00:00+0000 (dev)"
fi
echo "export const LIB_SHA = '${sha}' // pragma: allowlist secret" >> src/metadata.ts
echo "export const LIB_BUILT_AT = '${build_at}'" >> src/metadata.ts
