#!/usr/bin/env sh

version=$(jq -r '.version' package.json)
echo "/**" > src/metadata.ts
echo " * These values are used for the default footer in Slack message and in logging." >> src/metadata.ts
echo " *" >> src/metadata.ts
echo " * @privateRemarks" >> src/metadata.ts
echo " * This file is autogenerated by scripts/save-metadata.sh" >> src/metadata.ts
echo " * Do not edit it manually!" >> src/metadata.ts
echo " *" >> src/metadata.ts
echo " * @internal" >> src/metadata.ts
echo " */" >> src/metadata.ts
echo "export const LIB_VERSION = '${version}'" >> src/metadata.ts
