#!/usr/bin/env sh

version=$(jq -r '.version' package.json)
echo "/**" > src/version.ts
echo " * This value is used for the default footer in Slack message." >> src/version.ts
echo " *" >> src/version.ts
echo " * @privateRemarks" >> src/version.ts
echo " * This file is autogenerated by scripts/save-version.sh" >> src/version.ts
echo " * Do not edit it manually!" >> src/version.ts
echo " *" >> src/version.ts
echo " * @internal" >> src/version.ts
echo " */" >> src/version.ts
echo "export const LIB_VERSION = '${version}'" >> src/version.ts
