// Copyright (c) Yevhen Fabizhevskyi. All rights reserved. Licensed under the MIT license.

/**
 * Sarif to Slack message converter library.
 *
 * @remarks
 * This library provides a service to send a Slack messages based on the provided
 * SARIF (Static Analysis Results Interchange Format) files.
 *
 * @example
 * ```typescript
 * import { SarifToSlackService } from 'sarif-to-slack';
 *
 * const service = await SarifToSlackService.create({
 *   webhookUrl: 'https://hooks.slack.com/services/your/webhook/url',
 *   sarifPath: 'path/to/your/sarif/file.sarif',
 *   logLevel: 'info',
 *   username: 'SARIF Bot',
 *   iconUrl: 'https://example.com/icon.png',
 *   color: '#36a64f',
 *   header: {
 *     include: true,
 *     value: 'SARIF Analysis Results'
 *   },
 *   footer: {
 *     include: true,
 *     value: 'Generated by @fabasoad/sarif-to-slack'
 *   },
 *   actor: {
 *     include: true,
 *     value: 'fabasoad'
 *   },
 *   run: {
 *     include: true
 *   },
 * });
 * await service.sendAll();
 * ```
 *
 * @see {@link SarifToSlackService}
 *
 * @packageDocumentation
 */
export { SarifToSlackService } from './SarifToSlackService'
export {
  IncludeAwareProps,
  IncludeAwareWithValueProps,
  LogLevel,
  Sarif,
  SarifToSlackServiceOptions,
  SlackMessage,
} from './types'
