// Copyright (c) Yevhen Fabizhevskyi. All rights reserved. Licensed under the MIT license.

/**
 * Sarif to Slack message converter library.
 *
 * @remarks
 * This library provides a service to send a Slack messages based on the provided
 * SARIF (Static Analysis Results Interchange Format) files.
 *
 * @example
 * ```typescript
 * import { SarifToSlackService, FooterType } from '@fabasoad/sarif-to-slack';
 *
 * const service = await SarifToSlackService.create({
 *   webhookUrl: 'https://hooks.slack.com/services/your/webhook/url',
 *   sarifPath: 'path/to/your/sarif/file.sarif',
 *   username: 'SARIF Bot',
 *   iconUrl: 'https://example.com/icon.png',
 *   color: '#36a64f',
 *   log: {
 *     level: LogLevel.Info,
 *     template: '[{{logLevelName}}] [{{name}}] {{dateIsoStr}} ',
 *     colored: false,
 *   },
 *   header: {
 *     include: true,
 *     value: 'SARIF Analysis Results'
 *   },
 *   footer: {
 *     include: true,
 *     type: FooterType.PLAIN_TEXT,
 *     value: 'Generated by @fabasoad/sarif-to-slack'
 *   },
 *   actor: {
 *     include: true,
 *     value: 'fabasoad'
 *   },
 *   run: {
 *     include: true
 *   },
 *   representation: RepresentationType.CompactGroupByToolNamePerSeverity,
 * });
 * await service.sendAll();
 * ```
 *
 * @see {@link SarifToSlackClient}
 *
 * @packageDocumentation
 */
export {
  Color,
  ColorOptions,
  ColorGroupByLevel,
  ColorGroupBySeverity
} from './model/Color'
export { SarifToSlackClient } from './SarifToSlackClient'
export {
  FooterOptions,
  FooterType,
  IncludeAwareOptions,
  IncludeAwareWithValueOptions,
  LogLevel,
  LogOptions,
  RepresentationType,
  SarifOptions,
  SarifToSlackClientOptions,
  SendIf,
  SlackMessage,
} from './types'
