/**
 * These values are used for the default footer in Slack message and in logging.
 *
 * @privateRemarks
 * This file is autogenerated by scripts/save-metadata.sh
 * Do not edit it manually!
 *
 * @internal
 */
export const LIB_VERSION = '0.2.3'
export const LIB_SHA = '70fcd62191c85b119fe3c8f5eae82c5f78c63a26' // pragma: allowlist secret
export const LIB_BUILT_AT = '2025-07-30T23:16:28+0900'
