/**
 * These values are used for the default footer in Slack message and in logging.
 *
 * @privateRemarks
 * This file is autogenerated by scripts/save-metadata.sh
 * Do not edit it manually!
 *
 * @internal
 */
export const LIB_VERSION = '0.2.3'
export const LIB_SHA = 'foo (dev)' // pragma: allowlist secret
export const LIB_BUILT_AT = '1900-01-01T00:00:00+0000 (dev)'
