/**
 * These values are used for the default footer in Slack message and in logging.
 *
 * @privateRemarks
 * This file is autogenerated by scripts/save-metadata.sh
 * Do not edit it manually!
 *
 * @internal
 */
export const LIB_VERSION = '0.2.3'
export const LIB_SHA = '69e5daf01d93fb764fdfa93e2fe1f2beeaff7193' // pragma: allowlist secret
export const LIB_BUILT_AT = '2025-07-30T23:15:40+0900'
