/**
 * This value is used for the default footer in Slack message.
 *
 * @privateRemarks
 * This file is autogenerated by scripts/save-version.sh
 * Do not edit it manually!
 *
 * @internal
 */
export const LIB_VERSION = '0.2.2'
