---
name: Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      bump-strategy:
        description: "Type of version bump to apply"
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  publish:
    name: Release ${{ github.event.inputs.bump-strategy }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Bump version
        run: |
          git config user.email "fabasoad@gmail.com"
          git config user.name "fabasoad"
          npm run version:${{ github.event.inputs.bump-strategy }}

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      # Publish to GitHub Packages
      - name: Setup .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "registry=https://npm.pkg.github.com" >> .npmrc

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
  github:
    name: GitHub
    needs: [publish]
    uses: fabasoad/reusable-workflows/.github/workflows/wf-github-release.yml@main
    with:
      bump-tags: false
