---
name: Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      bump-strategy:
        description: "Type of version bump to apply"
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  publish:
    name: Release ${{ github.event.inputs.bump-strategy }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    outputs:
      ref: ${{ steps.tag.outputs.ref }}
      ref-name: ${{ steps.tag.outputs.ref-name }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          git config user.email "fabasoad@gmail.com"
          git config user.name "fabasoad"
          npm run version:${{ github.event.inputs.bump-strategy }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v3

      - name: Get version
        id: tag
        run: |
          version=$(jq -r '.version' package.json)
          echo "ref=refs/tags/v${version}" >> "$GITHUB_OUTPUT"
          echo "ref-name=v${version}" >> "$GITHUB_OUTPUT"

      - name: Publish to npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --registry=https://registry.npmjs.org/ --access public

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com/
  github:
    name: GitHub
    needs: [publish]
    uses: fabasoad/reusable-workflows/.github/workflows/wf-github-release.yml@main
    with:
      bump-tags: false
      ref: ${{ needs.publish.outputs.ref }}
      ref-name: ${{ needs.publish.outputs.ref-name }}
