---
name: Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      bump-strategy:
        description: "Type of version bump to apply"
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  publish:
    name: Release ${{ github.event.inputs.bump-strategy }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    outputs:
      ref: ${{ steps.metadata.outputs.ref }}
      ref-name: ${{ steps.metadata.outputs.ref-name }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        env:
          BUMP_STRATEGY: "${{ github.event.inputs.bump-strategy }}"
        run: |
          git config user.email "fabasoad@gmail.com"
          git config user.name "fabasoad"
          npm run version:${BUMP_STRATEGY}

      - name: Install jq
        uses: dcarbone/install-jq-action@v3

      - name: Get metadata
        id: metadata
        run: |
          version=$(jq -r '.version' package.json)
          echo "ref=refs/tags/v${version}" >> "$GITHUB_OUTPUT"
          echo "ref-name=v${version}" >> "$GITHUB_OUTPUT"

      - name: Publish to npm registry
        uses: JS-DevTools/npm-publish@v4
        with:
          token: "${{ secrets.NPM_TOKEN }}"

      - name: Publish to GitHub Packages
        uses: JS-DevTools/npm-publish@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          registry: "https://npm.pkg.github.com"
  github:
    name: GitHub
    needs: [publish]
    uses: fabasoad/reusable-workflows/.github/workflows/wf-github-release.yml@main
    with:
      bump-tags: false
      ref: ${{ needs.publish.outputs.ref }}
      ref-name: ${{ needs.publish.outputs.ref-name }}
